### ISSUE TITLE
In what file i need to input my server URL ?

### ISSUE THREAD

**Issue by locodice13** [bfla/whatsnoodle#3]
I do not see where to put the server URL/ip on the client code. Can you help me?

**Comment by bfla** [comment]
Sure, happy to help.  What is your question exactly?  Were you trying to deploy it?  (The old deployment command I wrote no longer works because Meteor eliminated its free hosting service a couple weeks ago, which is sad because it was awesome.)

**Comment by bfla** [comment]
I'm going to close this issue but feel free to message me if I can be of assistance.  :)
